version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20 # Specify the Go version you're using

  pre_build:
    commands:
      - echo "Installing dependencies"
      - go mod download

  build:
    commands:
      - echo "Building the Go application"
      - go build -o main main.go

  post_build:
    commands:
      - echo "Running tests"

artifacts:
  files:
    - main
